version: '3.8'

services:
  # Frontend React application
  frontend:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./env.sh:/docker-entrypoint.d/40-env.sh
    environment:
      - API_URL=http://localhost:5000
      - BACKEND_URL=http://localhost:5000
      - APP_ENV=production
    restart: unless-stopped
    networks:
      - app-network
    # Add this command to ensure proper permissions and execution
    command: sh -c "chmod +x /docker-entrypoint.d/40-env.sh && nginx -g 'daemon off;'"

  # Backend API service
  backend:
    image: node:22-alpine
    working_dir: /app
    volumes:
      - ./backend:/app
    ports:
      - "5000:5000"
    command: sh -c "npm install dotenv && npm install && npm start"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb+srv://movieapp:btth1122@ahmedcluster.rdukguv.mongodb.net/moviedb?retryWrites=true&w=majority&appName=ahmedcluster
      - JWT_SECRET=secretkey@123
      - PORT=5000
    # depends_on:
    #   - db
    restart: unless-stopped
    networks:
      - app-network

  # Database service
  # db:
  #   image: mongo:latest
  #   volumes:
  #     - mongodb_data:/data/db
  #   ports:
  #     - "27017:27017"
  #   restart: unless-stopped
  #   networks:
  #     - app-network

# Define a network for the services
networks:
  app-network:
    driver: bridge

# Define volumes for persistent data
volumes:
  mongodb_data:

